apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageview
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: pageview
        image: mlemarec/pageview:v0.0.2