apiVersion: v1
kind: Pod
metadata:
  name: activity601-pod01
  labels:
    team: 'dev'
    critical: 'n'
    environment: 'production'
spec:
  containers:
  - name: activity601-pod01
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.25"