apiVersion: v1
kind: Pod
metadata:
  name: backend-production
  labels:
    environment: production
    role: backend
spec:
  containers:
  - name: application-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.25"