apiVersion: v1
kind: Pod
metadata:
  name: front-staging
  labels:
    environment: staging
    role: frontend
spec:
  containers:
  - name: application-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.25"