apiVersion: v1
kind: Pod
metadata:
  name: pod-without-initial-labels
spec:
  containers:
  - name: first-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"