apiVersion: v1
kind: Pod
metadata:
  name: activity501
  labels:
    name: activity501
spec:
  restartPolicy: OnFailure
  containers:
  - name: activity501
    image: packtworkshops/the-kubernetes-workshop:custom-application-for-pods-chapter
    resources:
      limits:
        memory: "256Mi"
        cpu: "1"
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 20
      periodSeconds: 10
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 20
      periodSeconds: 1