apiVersion: v1
kind: Pod
metadata:
  name: resource-requirements-pod
  labels:
    name: resource-requirements-pod
spec:
  containers:
  - name: resource-requirements-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "1"
      requests:
        memory: "64Mi"
        cpu: "0.5"