apiVersion: v1
kind: Pod
metadata:
  name: command-pod
  labels:
    name: command-pod
spec:
  containers:
  - name: container-with-command
    image: ubuntu
    command:
    - /bin/bash
    - -ec
    - while :; do echo "--- $(date) ---"; sleep 5; done