apiVersion: v1
kind: Service
metadata:
  name: nginx-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: nginx
    environment: production
  ports:
  - port: 80
    targetPort: 80
  clusterIP: 10.96.0.5