apiVersion: v1
kind: Pod
metadata:
  name: pod-matching-replicaset
  labels:
    environment: production
spec:
  containers:
  - name: first-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"